os: linux
dist: xenial
language: go

go:
  - 1.12.x
  - 1.13.x
  - tip

jobs:
  allow_failures:
    - go: tip

env:
  - GO111MODULE=on

go_import_path: github.com/Devoter/thlp/v4

script:
  - go test -v ./...
